### ISSUE TITLE
Is there any guide to install kumparanian on Windows?

### ISSUE THREAD

**Issue by okzapradhana** [kumparan/kumparanian#18]
Hello, based on the ds test which needs to install kumparanian. I did install them by "pip install kumparanian" command . But i got this error 
![image](https://user-images.githubusercontent.com/22886492/54004989-4b87e400-418a-11e9-8a25-09ba1d6720a9.png)

![image](https://user-images.githubusercontent.com/22886492/54005014-5fcbe100-418a-11e9-99ed-d57a14f9932b.png)

I dont understand why this happened when install kumparanian , is there any solution or guide to install kumparanian on windows? Because i think this issue is happening on Windows. 

Thank you and I would be happy to know your answer/solution.

**Comment by rubiagatra** [comment]
Are you already install visual c++ 14.0 ?

**Comment by okzapradhana** [comment]
I've checked my Visual c++ on Control Panel and I think It was installed before

![image](https://user-images.githubusercontent.com/22886492/54009383-2ea8dc00-419d-11e9-8c53-c632261ead8e.png)

I also test it by installing visual c++ again and the messages shown that i have to uninstall the current visual c++ first.

**Comment by ridhofadilah** [comment]
did you use python 3.7? try using python 3.6

**Comment by okzapradhana** [comment]
Yes, Im using 3.7.1 right now.

![image](https://user-images.githubusercontent.com/22886492/54022130-6119ff80-41c4-11e9-9847-af191b39279b.png)

SoI need to reinstall my Python, isn't it?

**Comment by ridhofadilah** [comment]
you didn't need to reinstall python version. just keep both version for python 3.7 and 3.6. then run, the following command to install kumparanian: pip3.6 install kumparanian.
If you want to run the python file with python 3.6, use this command: python3.6 YOUR_FILENAME.py

**Comment by okzapradhana** [comment]
Okay, thank you so much for helping this case.

![image](https://user-images.githubusercontent.com/22886492/54023896-bc4df100-41c8-11e9-9e47-2b166fb8dbad.png)

I think the kumparanian has been installed successfully using python 3.6 ver.

Thank you.

**Comment by ridhofadilah** [comment]
my pleasure
